const items = [
  {
      id: '001',
      image: 'images/milkbikis.jpg',
      company: 'BRITANNIA',
      item_name: 'Classic Milky Sandwich',
      original_price: 50,
      current_price: 45,
      discount_percentage:10,
      return_period: 1,
      delivery_date: '20 nov 2023',
      rating: {
          stars: 4.5,
          count: 1400,
      },
  },
  {
      id: '002',
      image: 'images/lays.jpeg',
      company: 'LAYS',
      item_name: 'American style creame & Onion',
      original_price: 120,
      current_price: 100,
      discount_percentage: 18,
      return_period: 1,
      delivery_date: '20 nov 2023',
      rating: {
          stars: 4.3,
          count: 24,
      },
  },
  {
      id: '003',
      image: 'images/amulmilk.jpg',
      company: 'AMUL',
      item_name: 'Amul Gold',
      original_price: 27,
      current_price: 26,
      discount_percentage: 4,
      return_period: 1,
      delivery_date: '20 nov 2023',
      rating: {
          stars: 4.1,
          count: 249,
      },
  },
  {
      id: '004',
      image: 'images/refinedoil.jpg',
      company: 'SAFFOLA',
      item_name: 'Saffola Gold',
      original_price: 709,
      current_price: 709,
      discount_percentage: 0,
      return_period: 3,
      delivery_date: '21 Nov 2023',
      rating: {
          stars: 5.0,
          count: 10,
      },
  },
  {
      id: '005',
      image: 'images/maggi.webp',
      company: 'MAGGI',
      item_name: 'Noodles',
      original_price: 14,
      current_price: 13,
      discount_percentage:8 ,
      return_period: 2,
      delivery_date: '20 Nov 2023',
      rating: {
          stars: 4.2,
          count: 3500,
      },
  },
  {
      id: '006',
      image: 'images/thumsup.webp',
      company: 'Coca Cola',
      item_name: 'Thums Up Can',
      original_price: 40,
      current_price: 40,
      discount_percentage: 0,
      return_period: 0,
      delivery_date: '20 Nov 2023',
      rating: {
          stars: 0.0,
          count: 0,
      },
  },
  {
      id: '007',
      image: 'images/surfexcel.jpeg',
      company: 'SURF EXCEL',
      item_name: 'Surf Excel Easy Wash',
      original_price: 165,
      current_price: 162,
      discount_percentage: 5,
      rating: {
          stars: 4.2,
          count: 388,
      },
  },
  {
      id: '008',
      image: 'images/bread.webp',
      company: 'ENGLISH OVEN',
      item_name: 'Brown Bread (400g)',
      original_price: 36,
      current_price: 33,
      discount_percentage:8 ,
      return_period: 0,
      delivery_date: '20 Nov 2023',
      rating: {
          stars: 4.2,
          count: 5200,
      },
  }
];